using System;
using System.Collections.Generic;

namespace DCWaterMobile.LocalData.Models
{
    public partial class WORKORDER
    {
        public long C_WORKORDERID_LOCAL_ { get; set; }
        public string WONUM { get; set; }
        public string PARENT { get; set; }
        public string STATUS { get; set; }
        public System.DateTime STATUSDATE { get; set; }
        public string WORKTYPE { get; set; }
        public string LEADCRAFT { get; set; }
        public string DESCRIPTION { get; set; }
        public string LOCATION { get; set; }
        public string JPNUM { get; set; }
        public Nullable<System.DateTime> FAILDATE { get; set; }
        public string CHANGEBY { get; set; }
        public Nullable<System.DateTime> CHANGEDATE { get; set; }
        public double ESTDUR { get; set; }
        public double ESTLABHRS { get; set; }
        public double ESTMATCOST { get; set; }
        public double ESTLABCOST { get; set; }
        public double ESTTOOLCOST { get; set; }
        public string PMNUM { get; set; }
        public double ACTLABHRS { get; set; }
        public double ACTMATCOST { get; set; }
        public double ACTLABCOST { get; set; }
        public double ACTTOOLCOST { get; set; }
        public long HASCHILDREN { get; set; }
        public double OUTLABCOST { get; set; }
        public double OUTMATCOST { get; set; }
        public double OUTTOOLCOST { get; set; }
        public long HISTORYFLAG { get; set; }
        public string CONTRACT { get; set; }
        public Nullable<long> WOPRIORITY { get; set; }
        public Nullable<System.DateTime> TARGCOMPDATE { get; set; }
        public Nullable<System.DateTime> TARGSTARTDATE { get; set; }
        public string WOEQ1 { get; set; }
        public string WOEQ2 { get; set; }
        public string WOEQ3 { get; set; }
        public string WOEQ4 { get; set; }
        public Nullable<double> WOEQ5 { get; set; }
        public Nullable<System.DateTime> WOEQ6 { get; set; }
        public string WOEQ7 { get; set; }
        public string WOEQ8 { get; set; }
        public string WOEQ9 { get; set; }
        public string WOEQ10 { get; set; }
        public string WOEQ11 { get; set; }
        public string WOEQ12 { get; set; }
        public string WO1 { get; set; }
        public string WO3 { get; set; }
        public string WO4 { get; set; }
        public string WO7 { get; set; }
        public string WO9 { get; set; }
        public string WO10 { get; set; }
        public string REPORTEDBY { get; set; }
        public Nullable<System.DateTime> REPORTDATE { get; set; }
        public string PHONE { get; set; }
        public string PROBLEMCODE { get; set; }
        public string CALENDAR { get; set; }
        public long DOWNTIME { get; set; }
        public Nullable<System.DateTime> ACTSTART { get; set; }
        public Nullable<System.DateTime> ACTFINISH { get; set; }
        public Nullable<System.DateTime> SCHEDSTART { get; set; }
        public Nullable<System.DateTime> SCHEDFINISH { get; set; }
        public Nullable<double> REMDUR { get; set; }
        public string CREWID { get; set; }
        public string SUPERVISOR { get; set; }
        public Nullable<System.DateTime> WOEQ13 { get; set; }
        public Nullable<double> WOEQ14 { get; set; }
        public string WOJP1 { get; set; }
        public string WOJP2 { get; set; }
        public string WOJP3 { get; set; }
        public Nullable<double> WOJP4 { get; set; }
        public Nullable<System.DateTime> WOJP5 { get; set; }
        public string WOL1 { get; set; }
        public string WOL2 { get; set; }
        public Nullable<double> WOL3 { get; set; }
        public Nullable<System.DateTime> WOL4 { get; set; }
        public string WOLABLNK { get; set; }
        public Nullable<System.DateTime> RESPONDBY { get; set; }
        public Nullable<long> CALCPRIORITY { get; set; }
        public long CHARGESTORE { get; set; }
        public string FAILURECODE { get; set; }
        public string WOLO1 { get; set; }
        public string WOLO2 { get; set; }
        public string WOLO3 { get; set; }
        public string WOLO4 { get; set; }
        public string WOLO5 { get; set; }
        public Nullable<double> WOLO6 { get; set; }
        public Nullable<System.DateTime> WOLO7 { get; set; }
        public Nullable<double> WOLO8 { get; set; }
        public string WOLO9 { get; set; }
        public Nullable<long> WOLO10 { get; set; }
        public string GLACCOUNT { get; set; }
        public double ESTSERVCOST { get; set; }
        public double ACTSERVCOST { get; set; }
        public long DISABLED { get; set; }
        public double ESTATAPPRLABHRS { get; set; }
        public double ESTATAPPRLABCOST { get; set; }
        public double ESTATAPPRMATCOST { get; set; }
        public double ESTATAPPRTOOLCOST { get; set; }
        public double ESTATAPPRSERVCOST { get; set; }
        public Nullable<long> WOSEQUENCE { get; set; }
        public long HASFOLLOWUPWORK { get; set; }
        public string WORTS1 { get; set; }
        public string WORTS2 { get; set; }
        public string WORTS3 { get; set; }
        public Nullable<System.DateTime> WORTS4 { get; set; }
        public Nullable<double> WORTS5 { get; set; }
        public string SOURCESYSID { get; set; }
        public string OWNERSYSID { get; set; }
        public Nullable<System.DateTime> PMDUEDATE { get; set; }
        public Nullable<System.DateTime> PMEXTDATE { get; set; }
        public Nullable<System.DateTime> PMNEXTDUEDATE { get; set; }
        public string WORKLOCATION { get; set; }
        public string WO11 { get; set; }
        public long WO13 { get; set; }
        public long WO14 { get; set; }
        public long WO15 { get; set; }
        public long WO16 { get; set; }
        public long WO17 { get; set; }
        public long WO18 { get; set; }
        public long WO19 { get; set; }
        public long WO20 { get; set; }
        public string EXTERNALREFID { get; set; }
        public string SENDERSYSID { get; set; }
        public string FINCNTRLID { get; set; }
        public string GENERATEDFORPO { get; set; }
        public Nullable<long> GENFORPOLINEID { get; set; }
        public string ORGID { get; set; }
        public string SITEID { get; set; }
        public Nullable<long> TASKID { get; set; }
        public string INSPECTOR { get; set; }
        public Nullable<double> MEASUREMENTVALUE { get; set; }
        public Nullable<System.DateTime> MEASUREDATE { get; set; }
        public string OBSERVATION { get; set; }
        public string POINTNUM { get; set; }
        public string WOJO1 { get; set; }
        public string WOJO2 { get; set; }
        public string WOJO3 { get; set; }
        public Nullable<double> WOJO4 { get; set; }
        public string WOJO5 { get; set; }
        public string WOJO6 { get; set; }
        public string WOJO7 { get; set; }
        public string WOJO8 { get; set; }
        public long ISTASK { get; set; }
        public string SERVICE { get; set; }
        public string ORIGPROBLEMTYPE { get; set; }
        public string CISNUM { get; set; }
        public Nullable<System.DateTime> MISSUTILITYDATE { get; set; }
        public string MISSUTILITYNUM { get; set; }
        public long MISSUTILITYEMERG { get; set; }
        public string MAPNUM { get; set; }
        public string RECEIVEDVIA { get; set; }
        public string LOCATIONDETAILS { get; set; }
        public string OTHERCONTACT { get; set; }
        public long WATERDISCOLORED { get; set; }
        public string WATERCOLOR { get; set; }
        public string DISCOLORHOTCOLD { get; set; }
        public long RUN15MINUTES { get; set; }
        public long PARTICLESINWATER { get; set; }
        public string PARTICLECOLOR { get; set; }
        public long WATERCLOUDY { get; set; }
        public long WATERODOR { get; set; }
        public string TYPEODOR { get; set; }
        public long WATERCAUSERASH { get; set; }
        public long PERSONSEENDOCTOR { get; set; }
        public string MEDICALREPORT { get; set; }
        public string CONNECTIONTYPE { get; set; }
        public string PROBLEMBEGAN { get; set; }
        public string PROBLEMLOC { get; set; }
        public long PROBLEMTHRUOUT { get; set; }
        public string LOCALIZEDWHERE { get; set; }
        public long WATERTREATMENT { get; set; }
        public string TYPETREATMENT { get; set; }
        public Nullable<double> MEASUREMENTVALUE2 { get; set; }
        public Nullable<double> MEASUREMENTVALUE3 { get; set; }
        public string SAMPLELOCTYPE { get; set; }
        public long PETROLEUMODOR { get; set; }
        public string CUTNUM { get; set; }
        public Nullable<long> DISTANCE { get; set; }
        public string FINALPOSITION { get; set; }
        public Nullable<double> NUMBEROFTURNS { get; set; }
        public long WATERTASTE { get; set; }
        public string WATERTASTEDESC { get; set; }
        public string FUND { get; set; }
        public string OUTLETDIA { get; set; }
        public Nullable<double> VELOCITYPRES { get; set; }
        public long SNAKELINE { get; set; }
        public long JETLINE { get; set; }
        public string PROBLEMSIDE { get; set; }
        public Nullable<double> MEASUREMENTVALUE4 { get; set; }
        public long VALIDATED { get; set; }
        public string CUSTOMERSTREET { get; set; }
        public string CUSTOMERCITY { get; set; }
        public string CUSTOMERSTATE { get; set; }
        public string CUSTOMERZIP { get; set; }
        public string CUSTOMEREMAIL { get; set; }
        public string ALTPHONEFAX { get; set; }
        public string OTHERCOMPANY { get; set; }
        public string PLUMBERNAME { get; set; }
        public string PLUMBERLICNUM { get; set; }
        public long SEWERRELIEVED { get; set; }
        public string SNAKELOC { get; set; }
        public long SNAKETOSEWER { get; set; }
        public long CLEANOUT { get; set; }
        public string CLEANOUTLOC { get; set; }
        public long RUNNINGTRAP { get; set; }
        public string RUNNINGTRAPLOC { get; set; }
        public string EQUIPMENTUSED { get; set; }
        public string JUSTIFICATION { get; set; }
        public long DEBRIS { get; set; }
        public string DEBRISDESC { get; set; }
        public string WEATHERCOND { get; set; }
        public string WINDS { get; set; }
        public Nullable<long> TEMPERATURE { get; set; }
        public long PRECIPITATION { get; set; }
        public string ENGINEERCOMPANY { get; set; }
        public string DEVELOPERCOMPANY { get; set; }
        public string DEVELOPERCONTACT { get; set; }
        public string DEVELOPERPHONE { get; set; }
        public string AGENCYID { get; set; }
        public string RECEIVEDAT { get; set; }
        public string CONTRACTORCONTACT { get; set; }
        public string ENUM { get; set; }
        public string PIPETYPE { get; set; }
        public Nullable<System.DateTime> PERMITDATE { get; set; }
        public long ASBUILTREQD { get; set; }
        public long ASBUILTRECD { get; set; }
        public string CONTRACTORPHONE { get; set; }
        public string PROJECTTYPE { get; set; }
        public Nullable<long> ASSETLOCPRIORITY { get; set; }
        public string ASSETNUM { get; set; }
        public string BACKOUTPLAN { get; set; }
        public string CLASSSTRUCTUREID { get; set; }
        public string COMMODITY { get; set; }
        public string COMMODITYGROUP { get; set; }
        public string ENVIRONMENT { get; set; }
        public long HASLD { get; set; }
        public long INTERRUPTIBLE { get; set; }
        public string JUSTIFYPRIORITY { get; set; }
        public string LANGCODE { get; set; }
        public string LEAD { get; set; }
        public string ONBEHALFOF { get; set; }
        public string ORIGRECORDCLASS { get; set; }
        public string ORIGRECORDID { get; set; }
        public string OWNER { get; set; }
        public string OWNERGROUP { get; set; }
        public long PARENTCHGSSTATUS { get; set; }
        public string PERSONGROUP { get; set; }
        public string REASONFORCHANGE { get; set; }
        public string RISK { get; set; }
        public string VENDOR { get; set; }
        public string VERIFICATION { get; set; }
        public string WHOMISCHANGEFOR { get; set; }
        public long WOACCEPTSCHARGES { get; set; }
        public string WOCLASS { get; set; }
        public string WOGROUP { get; set; }
        public long? WORKORDERID { get; set; }
        public string BKPCONTRACT { get; set; }
        public string CINUM { get; set; }
        public string FLOWACTION { get; set; }
        public long FLOWACTIONASSIST { get; set; }
        public long FLOWCONTROLLED { get; set; }
        public Nullable<long> JOBTASKID { get; set; }
        public string LAUNCHENTRYNAME { get; set; }
        public string NEWCHILDCLASS { get; set; }
        public string ROUTE { get; set; }
        public Nullable<long> ROUTESTOPID { get; set; }
        public long SUSPENDFLOW { get; set; }
        public string TARGETDESC { get; set; }
        public long WOISSWAP { get; set; }
        public string FIRSTAPPRSTATUS { get; set; }
        public string PMCOMTYPE { get; set; }
        public string PMCOMSTATE { get; set; }
        public string PMCOMBPELACTNAME { get; set; }
        public long PMCOMBPELENABLED { get; set; }
        public long PMCOMBPELINPROG { get; set; }
        public string CONPERMITNUM { get; set; }
        public string OCCPERMITNUM { get; set; }
        public string CALCORGID { get; set; }
        public string CALCCALENDAR { get; set; }
        public string CALCSHIFT { get; set; }
        public string RESTORATIONREQD { get; set; }
        public Nullable<long> CONTR_REL_NUM { get; set; }
        public long DCW_LWBUDGETCHECK { get; set; }
        public long DCW_SENDMATL2LW { get; set; }
        public string DCW_SNAKEDIST2BLCKG { get; set; }
        public string CONTRACTORJUSTIFICATION { get; set; }
        public Nullable<double> COMPLEXITY { get; set; }
        public long DCW_UTILITYSTRIKE { get; set; }
        public Nullable<long> DCW_REVISEDPRIORITY { get; set; }
        public string REPFACSITEID { get; set; }
        public string REPAIRFACILITY { get; set; }
        public Nullable<long> GENFORPOREVISION { get; set; }
        public string STOREROOMMTLSTATUS { get; set; }
        public string DIRISSUEMTLSTATUS { get; set; }
        public string WORKPACKMTLSTATUS { get; set; }
        public long IGNORESRMAVAIL { get; set; }
        public long IGNOREDIAVAIL { get; set; }
        public Nullable<double> ESTINTLABCOST { get; set; }
        public Nullable<double> ESTINTLABHRS { get; set; }
        public Nullable<double> ESTOUTLABHRS { get; set; }
        public Nullable<double> ESTOUTLABCOST { get; set; }
        public Nullable<double> ACTINTLABCOST { get; set; }
        public Nullable<double> ACTINTLABHRS { get; set; }
        public Nullable<double> ACTOUTLABHRS { get; set; }
        public Nullable<double> ACTOUTLABCOST { get; set; }
        public Nullable<double> ESTATAPPRINTLABCOST { get; set; }
        public Nullable<double> ESTATAPPRINTLABHRS { get; set; }
        public Nullable<double> ESTATAPPROUTLABHRS { get; set; }
        public Nullable<double> ESTATAPPROUTLABCOST { get; set; }
        public string ASSIGNEDOWNERGROUP { get; set; }
        public Nullable<System.DateTime> AVAILSTATUSDATE { get; set; }
        public Nullable<System.DateTime> LASTCOPYLINKDATE { get; set; }
        public long NESTEDJPINPROCESS { get; set; }
        public Nullable<long> PLUSCFREQUENCY { get; set; }
        public string PLUSCFREQUNIT { get; set; }
        public long PLUSCISMOBILE { get; set; }
        public Nullable<long> PLUSCJPREVNUM { get; set; }
        public long PLUSCLOOP { get; set; }
        public Nullable<System.DateTime> PLUSCNEXTDATE { get; set; }
        public Nullable<System.DateTime> PLUSCOVERDUEDATE { get; set; }
        public string PLUSCPHYLOC { get; set; }
        public long INCTASKSINSCHED { get; set; }
        public Nullable<System.DateTime> SNECONSTRAINT { get; set; }
        public Nullable<System.DateTime> FNLCONSTRAINT { get; set; }
        public string AMCREW { get; set; }
        public string CREWWORKGROUP { get; set; }
        public long REQASSTDWNTIME { get; set; }
        public long APPTREQUIRED { get; set; }
        public long AOS { get; set; }
        public long AMS { get; set; }
        public long LOS { get; set; }
        public long LMS { get; set; }
        public string PLUSSFEATURECLASS { get; set; }
        public long PLUSSISGIS { get; set; }
        public long DCW_CBASSIGNED { get; set; }
        public string ROWSTAMP { get; set; }
        public long C_record_state_ { get; set; }
        public string C_mobile_work_type_ { get; set; }
        public Nullable<long> C_ASSETNUM_LOCAL { get; set; }
        public Nullable<long> C_ORIGRECORDID_LOCAL_ { get; set; }

        // Related Records
        public virtual ICollection<WORKORDERSPEC> WorkorderSpecs { get; set; }
        public virtual ICollection<DOCLINK>  Doclinks { get; set; }
        public virtual FAILUREREMARK FailureRemark { get; set; }
        public virtual ICollection<FAILUREREPORT> FailureReports { get; set; }
        public virtual ICollection<LABTRAN> LabTrans { get; set; }
        public virtual ICollection<TOOLTRAN> ToolTrans { get; set; }
        public virtual ICollection<WOSTATUS> WoStatuses { get; set; }
        public virtual ASSET Asset { get; set; }
        public virtual WORKORDER Originator { get; set; }

    }
}
